#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 24 10:12:26 2022

@author: jordansiegel
"""

i = entiretaskloop.thisRepN

if condition[i] == 'Rej':
    pDislike = .7
    pLike = .3
    partner = partner_selected[i]
    blocklist = ['disliked'] * int(nTrials * pDislike) + ['liked'] * int(nTrials * pLike)
    random.shuffle(blocklist)
    feedback = random.sample(blocklist,30)
    block = 0 #before experiment 
elif condition[i] == 'Acc':
    pDislike = .3
    pLike = .7
    partner = partner_selected[i]
    blocklist = ['disliked'] * int(nTrials * pDislike) + ['liked'] * int(nTrials * pLike)
    random.shuffle(blocklist)
    feedback = random.sample(blocklist,30)
    #feedback = feedbacklist
    block = 0 #before experiment 
elif condition[i] == 'Neutral':
    pDislike = .5
    pLike = .5
    partner = partner_selected[i]
    blocklist = ['disliked'] * int(nTrials * pDislike) + ['liked'] * int(nTrials * pLike)
    random.shuffle(blocklist)
    feedback = random.sample(blocklist,30)
    #feedback = feedbacklist
    block = 0 #before experiment 

